/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.zerhusen.security.controller.bodega;

import org.zerhusen.model.bodega.Giro;
import org.zerhusen.security.repository.bodega.GiroRepository;
import java.text.ParseException;
import java.util.Collection;
import java.util.Optional;
import javax.annotation.PostConstruct;
import javax.validation.Valid;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.CrossOrigin;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import static org.springframework.web.bind.annotation.RequestMethod.DELETE;
import static org.springframework.web.bind.annotation.RequestMethod.GET;
import static org.springframework.web.bind.annotation.RequestMethod.POST;
import static org.springframework.web.bind.annotation.RequestMethod.PUT;
import org.springframework.web.bind.annotation.ResponseStatus;
import org.springframework.web.bind.annotation.RestController;

/**
 *
 * @author Ferenc
 */
@RestController
public class GiroController {

    @Autowired
    private GiroRepository repository;

    @PostConstruct
    public void init() throws ParseException {
        if(repository.findAll() != null){
        repository.save(new Giro(11111, "CULTIVO DE TRIGO"));
        repository.save(new Giro(11112, "CULTIVO DE MAIZ"));
        repository.save(new Giro(11113, "CULTIVO DE AVENA"));
        repository.save(new Giro(11114, "CULTIVO DE ARROZ"));
        repository.save(new Giro(11115, "CULTIVO DE CEBADA"));
        repository.save(new Giro(11119, "CULTIVO DE OTROS CEREALES"));
        repository.save(new Giro(11121, "CULTIVO FORRAJEROS EN PRADERAS NATURALES"));
        repository.save(new Giro(11122, "CULTIVO FORRAJEROS EN PRADERAS MEJORADAS O SEMBRADAS"));
        repository.save(new Giro(11131, "CULTIVO DE POROTOS O FRIJOL"));
        repository.save(new Giro(11132, "CULTIVO, PRODUCCIÓN DE LUPINO"));
        repository.save(new Giro(11139, "CULTIVO DE OTRAS LEGUMBRES"));
        repository.save(new Giro(11141, "CULTIVO DE PAPAS"));
        repository.save(new Giro(11142, "CULTIVO DE CAMOTES O BATATAS"));
        repository.save(new Giro(11149, "CULTIVO DE OTROS TUBÉRCULOS N.C.P"));
        repository.save(new Giro(11151, "CULTIVO DE RAPS"));
        repository.save(new Giro(11152, "CULTIVO DE MARAVILLA"));
        repository.save(new Giro(11159, "CULTIVO DE OTRAS OLEAGINOSAS N.C.P."));
        repository.save(new Giro(11160, "PRODUCCIÓN DE SEMILLAS DE CEREALES, LEGUMBRES, OLEAGINOSAS"));
        repository.save(new Giro(11191, "CULTIVO DE REMOLACHA"));
        repository.save(new Giro(11192, "CULTIVO DE TABACO"));
        repository.save(new Giro(11193, "CULTIVO DE FIBRAS VEGETALES INDUSTRIALES"));
        repository.save(new Giro(11194, "CULTIVO DE PLANTAS AROMÁTICAS O MEDICINALES"));
        repository.save(new Giro(11199, "OTROS CULTIVOS N.C.P."));
        repository.save(new Giro(11211, "CULTIVO TRADICIONAL DE HORTALIZAS FRESCAS"));
        repository.save(new Giro(11212, "CULTIVO DE HORTALIZAS EN INVERNADEROS Y CULTIVOS HIDROPONICOS"));
        repository.save(new Giro(11213, "CULTIVO ORGÁNICO DE HORTALIZAS"));
        repository.save(new Giro(11220, "CULTIVO DE PLANTAS VIVAS Y PRODUCTOS DE LA FLORICULTURA"));
        repository.save(new Giro(11230, "PRODUCCIÓN DE SEMILLAS DE FLORES, PRADOS, FRUTAS Y HORTALIZAS"));
        repository.save(new Giro(11240, "PRODUCCIÓN EN VIVEROS, EXCEPTO ESPECIES FORESTALES"));
        repository.save(new Giro(11250, "CULTIVO Y RECOLECCIÓN DE HONGOS, TRUFAS Y SAVIA, PRODUCCIÓN DE JARABE DE ARCE DE AZÚCAR Y AZÚCAR"));
        repository.save(new Giro(11311, "CULTIVO DE UVA DESTINADA A PRODUCCIÓN DE PISCO Y AGUARDIENTE"));
        repository.save(new Giro(11312, "CULTIVO DE UVA DESTINADA A PRODUCCIÓN DE VINO"));
        repository.save(new Giro(11313, "CULTIVO DE UVA DE MESA"));
        repository.save(new Giro(11321, "CULTIVO DE FRUTALES EN ÁRBOLES O ARBUSTOS CON CICLO DE VIDA MAYOR A UNA TEMPORADA"));
        repository.save(new Giro(11322, "CULTIVO DE FRUTALES MENORES EN PLANTAS CON CICLO DE VIDA DE UNA TEMPORADA"));
        repository.save(new Giro(11330, "CULTIVO DE PLANTAS CUYAS HOJAS O FRUTAS SE UTILIZAN PARA PREPARAR BEBIDAS"));
        repository.save(new Giro(11340, "CULTIVO DE ESPECIAS"));
        repository.save(new Giro(12111, "CRÍA DE GANADO BOVINO PARA LA PRODUCCIÓN LECHERA"));
        repository.save(new Giro(12112, "CRÍA DE GANADO PARA PRODUCCIÓN DE CARNE, O COMO GANADO REPRODUCTOR"));
        repository.save(new Giro(12120, "CRÍA DE GANADO OVINO Y/O EXPLOTACIÓN LANERA"));
        repository.save(new Giro(12130, "CRÍA DE EQUINOS (CABALLARES, MULARES)"));
        repository.save(new Giro(12210, "CRÍA DE PORCINOS"));
        repository.save(new Giro(12221, "CRÍA DE AVES DE CORRAL PARA LA PRODUCCIÓN DE CARNE"));
        repository.save(new Giro(12222, "CRÍA DE AVES DE CORRAL PARA LA PRODUCCIÓN DE HUEVOS"));
        repository.save(new Giro(12223, "CRÍA DE AVES FINAS O NO TRADICIONALES"));
        repository.save(new Giro(12230, "CRÍA DE ANIMALES DOMÉSTICOS, PERROS Y GATOS"));
        repository.save(new Giro(12240, "APICULTURA"));
        repository.save(new Giro(12250, "RANICULTURA, HELICICULTURA U OTRA ACTIVIDAD CON ANIMALES MENORES O INSECTOS"));
        repository.save(new Giro(12290, "OTRAS EXPLOTACIONES DE ANIMALES NO CLASIFICADOS EN OTRA PARTE, INCLUIDO SUS SUBPRODUCTOS"));
        repository.save(new Giro(13000, "EXPLOTACIÓN MIXTA"));
        repository.save(new Giro(14011, "SERVICIO DE CORTE Y ENFARDADO DE FORRAJE"));
        repository.save(new Giro(14012, "SERVICIO DE RECOLECCIÓN, EMPACADO, TRILLA, DESCASCARAMIENTO Y DESGRANE, Y SIMILARES"));
        repository.save(new Giro(14013, "SERVICIO DE ROTURACIÓN SIEMBRA Y SIMILARES"));
        repository.save(new Giro(14014, "DESTRUCCIÓN DE PLAGAS, PULVERIZACIONES, FUMIGACIONES U OTRAS"));
        repository.save(new Giro(14015, "COSECHA, PODA, AMARRE Y LABORES DE ADECUACIÓN DE LA PLANTA U OTRAS"));
        repository.save(new Giro(14019, "OTROS SERVICIOS AGRÍCOLAS N.C.P."));
        repository.save(new Giro(14021, "SERVICIOS DE ADIESTRAMIENTO, GUARDERÍA Y CUIDADOS DE MASCOTAS, EXCEPTO ACTIVIDADES VETERINARIAS"));
        repository.save(new Giro(14022, "SERVICIOS GANADEROS, EXCEPTO ACTIVIDADES VETERINARIAS"));
        repository.save(new Giro(15010, "CAZA DE MAMÍFEROS MARINOS, EXCEPTO BALLENAS"));
        repository.save(new Giro(15090, "CAZA ORDINARIA Y MEDIANTE TRAMPAS"));
        repository.save(new Giro(20010, "EXPLOTACIÓN DE BOSQUES"));
        repository.save(new Giro(20020, "RECOLECCIÓN DE PRODUCTOS FORESTALES SILVESTRES"));
        repository.save(new Giro(20030, "EXPLOTACIÓN DE VIVEROS DE ESPECIES FORESTALES"));
        repository.save(new Giro(20041, "SERVICIOS DE FORESTACIÓN"));
        repository.save(new Giro(20042, "SERVICIOS DE CORTA DE MADERA"));
        repository.save(new Giro(20043, "SERVICIOS DE CONTROL DE INCENDIOS FORESTALES"));
        repository.save(new Giro(20049, "OTRAS ACTIVIDADES DE SERVICIOS CONEXAS A LA SILVICULTURA N.C.P."));
        repository.save(new Giro(51010, "CULTIVO DE ESPECIES ACUÁTICAS EN CUERPO DE AGUA DULCE"));
        repository.save(new Giro(51020, "REPRODUCCIÓN Y CRIANZAS DE PECES MARINOS"));
        repository.save(new Giro(51030, "CULTIVO"));
        repository.save(new Giro(51040, "REPRODUCCIÓN Y CRÍA DE MOLUSCOS Y CRUSTACEOS."));
        repository.save(new Giro(51090, "SERVICIOS RELACIONADOS CON LA ACUICULTURA"));
        repository.save(new Giro(52010, "PESCA INDUSTRIAL"));
        repository.save(new Giro(52020, "ACTIVIDAD PESQUERA DE BARCOS FACTORÍAS"));
        repository.save(new Giro(52030, "PESCA ARTESANAL. EXTRACCIÓN DE RECURSOS ACUÁTICOS EN GENERAL, INCLUYE BALLENAS"));
        repository.save(new Giro(52040, "RECOLECCIÓN DE PRODUCTOS MARINOS"));
        repository.save(new Giro(52050, "SERVICIOS RELACIONADOS CON LA PESCA"));
        repository.save(new Giro(100000, "EXTRACCIÓN"));
        repository.save(new Giro(111000, "EXTRACCIÓN DE PETRÓLEO CRUDO Y GAS NATURAL"));
        repository.save(new Giro(112000, "ACTIVIDADES DE SERVICIOS RELACIONADAS CON LA EXTRACCIÓN DE PETRÓLEO Y GAS"));
        repository.save(new Giro(120000, "EXTRACCIÓN DE MINERALES DE URANIO Y TORIO"));
        repository.save(new Giro(131000, "EXTRACCIÓN DE MINERALES DE HIERRO"));
        repository.save(new Giro(132010, "EXTRACCIÓN DE ORO Y PLATA"));
        repository.save(new Giro(132020, "EXTRACCIÓN DE ZINC Y PLOMO"));
        repository.save(new Giro(132030, "EXTRACCIÓN DE MANGANESO"));
        repository.save(new Giro(132090, "EXTRACCIÓN DE OTROS MINERALES METALÍFEROS N.C.P."));
        repository.save(new Giro(133000, "EXTRACCIÓN DE COBRE"));
        repository.save(new Giro(141000, "EXTRACCIÓN DE PIEDRA"));
        repository.save(new Giro(142100, "EXTRACCIÓN DE NITRATOS Y YODO"));
        repository.save(new Giro(142200, "EXTRACCIÓN DE SAL"));
        repository.save(new Giro(142300, "EXTRACCIÓN DE LITIO Y CLORUROS"));
        repository.save(new Giro(142900, "EXPLOTACIÓN DE OTRAS MINAS Y CANTERAS N.C.P."));
        repository.save(new Giro(151110, "PRODUCCIÓN"));
        repository.save(new Giro(151120, "CONSERVACIÓN DE CARNES ROJAS (FRIGORÍFICOS)"));
        repository.save(new Giro(151130, "PRODUCCIÓN"));
        repository.save(new Giro(151140, "ELABORACIÓN DE CECINAS"));
        repository.save(new Giro(151210, "PRODUCCIÓN DE HARINA DE PESCADO"));
        repository.save(new Giro(151221, "FABRICACIÓN DE PRODUCTOS ENLATADOS DE PESCADO Y MARISCOS"));
        repository.save(new Giro(151222, "ELABORACIÓN DE CONGELADOS DE PESCADOS Y MARISCOS"));
        repository.save(new Giro(151223, "ELABORACIÓN DE PRODUCTOS AHUMADOS"));
        repository.save(new Giro(151230, "ELABORACIÓN DE PRODUCTOS EN BASE A VEGETALES ACUÁTICOS"));
        repository.save(new Giro(151300, "ELABORACIÓN Y CONSERVACIÓN DE FRUTAS"));
        repository.save(new Giro(151410, "ELABORACIÓN DE ACEITES Y GRASAS DE ORIGEN VEGETAL"));
        repository.save(new Giro(151420, "ELABORACIÓN DE ACEITES Y GRASAS DE ORIGEN ANIMAL"));
        repository.save(new Giro(151430, "ELABORACIÓN DE ACEITES Y GRASAS DE ORIGEN MARINO"));
        repository.save(new Giro(152010, "ELABORACIÓN DE LECHE"));
        repository.save(new Giro(152020, "ELABORACIÓN DE QUESOS"));
        repository.save(new Giro(152030, "FABRICACIÓN DE POSTRES A BASE DE LECHE (HELADOS"));
        repository.save(new Giro(153110, "ELABORACIÓN DE HARINAS DE TRIGO"));
        repository.save(new Giro(153120, "ACTIVIDADES DE MOLIENDA DE ARROZ"));
        repository.save(new Giro(153190, "ELABORACIÓN DE OTRAS MOLINERAS Y ALIMENTOS A BASE DE CEREALES"));
        repository.save(new Giro(153210, "ELABORACIÓN DE ALMIDONES Y PRODUCTOS DERIVADOS DEL ALMIDÓN"));
        repository.save(new Giro(153220, "ELABORACIÓN DE GLUCOSA Y OTROS AZÚCARES DIFERENTES DE LA REMOLACHA"));
        repository.save(new Giro(153300, "ELABORACIÓN DE ALIMENTOS PREPARADOS PARA ANIMALES"));
        repository.save(new Giro(154110, "FABRICACIÓN DE PAN"));
        repository.save(new Giro(154120, "FABRICACIÓN DE GALLETAS"));
        repository.save(new Giro(154200, "ELABORACIÓN DE AZÚCAR DE REMOLACHA O CANA"));
        repository.save(new Giro(154310, "ELABORACIÓN DE CACAO Y CHOCOLATES"));
        repository.save(new Giro(154320, "FABRICACIÓN DE PRODUCTOS DE CONFITERÍA"));
        repository.save(new Giro(154400, "ELABORACIÓN DE MACARRONES"));
        repository.save(new Giro(154910, "ELABORACIÓN DE TE"));
        repository.save(new Giro(154920, "ELABORACIÓN DE LEVADURAS NATURALES O ARTIFICIALES"));
        repository.save(new Giro(154930, "ELABORACIÓN DE VINAGRES"));
        repository.save(new Giro(154990, "ELABORACIÓN DE OTROS PRODUCTOS ALIMENTICIOS NO CLASIFICADOS EN OTRA PARTE"));
        repository.save(new Giro(155110, "ELABORACIÓN DE PISCOS (INDUSTRIAS PISQUERAS)"));
        repository.save(new Giro(155120, "ELABORACIÓN DE BEBIDAS ALCOHÓLICAS Y DE ALCOHOL ETÍLICO A PARTIR DE SUSTANCIAS FERMENTADAS Y OTROS"));
        repository.save(new Giro(155200, "ELABORACIÓN DE VINOS"));
        repository.save(new Giro(155300, "ELABORACIÓN DE BEBIDAS MALTEADAS"));
        repository.save(new Giro(155410, "ELABORACIÓN DE BEBIDAS NO ALCOHÓLICAS"));
        repository.save(new Giro(155420, "ENVASADO DE AGUA MINERAL NATURAL"));
        repository.save(new Giro(155430, "ELABORACIÓN DE HIELO"));
        repository.save(new Giro(160010, "FABRICACIÓN DE CIGARROS Y CIGARRILLOS"));
        repository.save(new Giro(160090, "FABRICACIÓN DE OTROS PRODUCTOS DEL TABACO"));
        repository.save(new Giro(171100, "PREPARACIÓN DE HILATURA DE FIBRAS TEXTILES, TEJEDURA PROD. TEXTILES"));
        repository.save(new Giro(171200, "ACABADO DE PRODUCTOS TEXTIL"));
        repository.save(new Giro(172100, "FABRICACIÓN DE ARTÍCULOS CONFECCIONADOS DE MATERIAS TEXTILES"));
        repository.save(new Giro(172200, "FABRICACIÓN DE TAPICES Y ALFOMBRA"));
        repository.save(new Giro(172300, "FABRICACIÓN DE CUERDAS"));
        repository.save(new Giro(172910, "FABRICACIÓN DE TEJIDOS DE USO INDUSTRIAL COMO TEJIDOS IMPREGNADOS"));
        repository.save(new Giro(172990, "FABRICACIÓN DE OTROS PRODUCTOS TEXTILES N.C.P."));
        repository.save(new Giro(173000, "FABRICACIÓN DE TEJIDOS DE PUNTO"));
        repository.save(new Giro(181010, "FABRICACIÓN DE PRENDAS DE VESTIR TEXTILES Y SIMILARES"));
        repository.save(new Giro(181020, "FABRICACIÓN DE PRENDAS DE VESTIR DE CUERO NATURAL"));
        repository.save(new Giro(181030, "FABRICACIÓN DE ACCESORIOS DE VESTIR"));
        repository.save(new Giro(181040, "FABRICACIÓN DE ROPA DE TRABAJO"));
        repository.save(new Giro(182000, "ADOBO Y TENIDOS DE PIELES, FABRICACIÓN DE ARTÍCULOS DE PIEL"));
        repository.save(new Giro(191100, "CURTIDO Y ADOBO DE CUEROS"));
        repository.save(new Giro(191200, "FABRICACIÓN DE MALETAS, BOLSOS DE MANO Y SIMILARES, ARTÍCULOS DE TALABARTERÍA Y GUARNICIONERÍA"));
        repository.save(new Giro(192000, "FABRICACIÓN DE CALZADO"));
        repository.save(new Giro(201000, "ASERRADO Y ACEPILLADURA DE MADERAS"));
        repository.save(new Giro(202100, "FABRICACIÓN DE TABLEROS"));
        repository.save(new Giro(202200, "FABRICACIÓN DE PARTES Y PIEZAS DE CARPINTERÍA PARA EDIFICIOS Y CONSTRUCCIONES"));
        repository.save(new Giro(202300, "FABRICACIÓN DE RECIPIENTES DE MADERA"));
        repository.save(new Giro(202900, "FABRICACIÓN DE OTROS PRODUCTOS DE MADERA, ARTÍCULOS DE CORCHO, PAJA Y MATERIALES TRENZABLES"));
        repository.save(new Giro(210110, "FABRICACIÓN DE CELULOSA Y OTRAS PASTAS DE MADERA"));
        repository.save(new Giro(210121, "FABRICACIÓN DE PAPEL DE PERIÓDICO"));
        repository.save(new Giro(210129, "FABRICACIÓN DE PAPEL Y CARTÓN N.C.P."));
        repository.save(new Giro(210200, "FABRICACIÓN DE PAPEL Y CARTÓN ONDULADO Y DE ENVASES DE PAPEL Y CARTÓN"));
        repository.save(new Giro(210900, "FABRICACIÓN DE OTROS ARTÍCULOS DE PAPEL Y CARTÓN"));
        repository.save(new Giro(221101, "EDICIÓN PRINCIPALMENTE DE LIBROS"));
        repository.save(new Giro(221109, "EDICIÓN DE FOLLETOS"));
        repository.save(new Giro(221200, "EDICIÓN DE PERIÓDICOS"));
        repository.save(new Giro(221300, "EDICIÓN DE GRABACIONES"));
        repository.save(new Giro(221900, "OTRAS ACTIVIDADES DE EDICIÓN"));
        repository.save(new Giro(222101, "IMPRESIÓN PRINCIPALMENTE DE LIBROS"));
        repository.save(new Giro(222109, "OTRAS ACTIVIDADES DE IMPRESIÓN N.C.P."));
        repository.save(new Giro(222200, "ACTIVIDADES DE SERVICIO RELACIONADA CON LA IMPRESIÓN"));
        repository.save(new Giro(223000, "REPRODUCCIÓN DE GRABACIONES"));
        repository.save(new Giro(231000, "FABRICACIÓN DE PRODUCTOS DE HORNOS COQUE"));
        repository.save(new Giro(232000, "FABRICACIÓN DE PRODUCTOS DE REFINACIÓN DE PETRÓLEO"));
        repository.save(new Giro(233000, "ELABORACIÓN DE COMBUSTIBLE NUCLEAR"));
        repository.save(new Giro(241110, "FABRICACIÓN DE CARBÓN VEGETAL"));
        repository.save(new Giro(241190, "FABRICACIÓN DE SUSTANCIAS QUÍMICAS BÁSICAS"));
        repository.save(new Giro(241200, "FABRICACIÓN DE ABONOS Y COMPUESTOS DE NITRÓGENO"));
        repository.save(new Giro(241300, "FABRICACIÓN DE PLÁSTICOS EN FORMAS PRIMARIAS Y DE CAUCHO SINTÉTICO"));
        repository.save(new Giro(242100, "FABRICACIÓN DE PLAGUICIDAS Y OTROS PRODUCTOS QUÍMICOS DE USO AGROPECUARIO"));
        repository.save(new Giro(242200, "FABRICACIÓN DE PINTURAS"));
        repository.save(new Giro(242300, "FABRICACIÓN DE PRODUCTOS FARMACEUTICOS"));
        repository.save(new Giro(242400, "FABRICACIONES DE JABONES Y DETERGENTES"));
        repository.save(new Giro(242910, "FABRICACIÓN DE EXPLOSIVOS Y PRODUCTOS DE PIROTECNIA"));
        repository.save(new Giro(242990, "FABRICACIÓN DE OTROS PRODUCTOS QUÍMICOS N.C.P."));
        repository.save(new Giro(243000, "FABRICACIÓN DE FIBRAS MANUFACTURADAS"));
        repository.save(new Giro(251110, "FABRICACIÓN DE CUBIERTAS Y CÁMARAS DE CAUCHO"));
        repository.save(new Giro(251120, "RECAUCHADO Y RENOVACIÓN DE CUBIERTAS DE CAUCHO"));
        repository.save(new Giro(251900, "FABRICACIÓN DE OTROS PRODUCTOS DE CAUCHO"));
        repository.save(new Giro(252010, "FABRICACIÓN DE PLANCHAS"));
        repository.save(new Giro(252020, "FABRICACIÓN DE TUBOS"));
        repository.save(new Giro(252090, "FABRICACIÓN DE OTROS ARTÍCULOS DE PLÁSTICO"));
        repository.save(new Giro(261010, "FABRICACIÓN"));
        repository.save(new Giro(261020, "FABRICACIÓN DE VIDRIO HUECO"));
        repository.save(new Giro(261030, "FABRICACIÓN DE FIBRAS DE VIDRIO"));
        repository.save(new Giro(261090, "FABRICACIÓN DE ARTÍCULOS DE VIDRIO N.C.P."));
        repository.save(new Giro(269101, "FABRICACIÓN DE PRODUCTOS DE CERÁMICA NO REFRACTARIA PARA USO NO ESTRUCTURAL CON FINES ORNAMENTALES"));
        repository.save(new Giro(269109, "FABRICACIÓN DE PRODUCTOS DE CERÁMICA NO REFRACTARIA PARA USO NO ESTRUCTURAL N.C.P."));
        repository.save(new Giro(269200, "FABRICACIÓN DE PRODUCTOS DE CERÁMICAS REFRACTARIA"));
        repository.save(new Giro(269300, "FABRICACIÓN DE PRODUCTOS DE ARCILLA Y CERÁMICAS NO REFRACTARIAS PARA USO ESTRUCTURAL"));
        repository.save(new Giro(269400, "FABRICACIÓN DE CEMENTO"));
        repository.save(new Giro(269510, "ELABORACIÓN DE HORMIGÓN"));
        repository.save(new Giro(269520, "FABRICACIÓN DE PRODUCTOS DE FIBROCEMENTO Y ASBESTOCEMENTO"));
        repository.save(new Giro(269530, "FABRICACIÓN DE PANELES DE YESO PARA LA CONSTRUCCIÓN"));
        repository.save(new Giro(269590, "FABRICACIÓN DE ARTÍCULOS DE CEMENTO Y YESO N.C.P."));
        repository.save(new Giro(269600, "CORTE"));
        repository.save(new Giro(269910, "FABRICACIÓN DE MEZCLAS BITUMINOSAS A BASE DE ASFALTO"));
        repository.save(new Giro(269990, "FABRICACIÓN DE OTROS PRODUCTOS MINERALES NO METÁLICOS N.C.P"));
        repository.save(new Giro(271000, "INDUSTRIAS BASICAS DE HIERRO Y ACERO"));
        repository.save(new Giro(272010, "ELABORACIÓN DE PRODUCTOS DE COBRE EN FORMAS PRIMARIAS."));
        repository.save(new Giro(272020, "ELABORACIÓN DE PRODUCTOS DE ALUMINIO EN FORMAS PRIMARIAS"));
        repository.save(new Giro(272090, "FABRICACIÓN DE PRODUCTOS PRIMARIOS DE METALES PRECIOSOS Y DE OTROS METALES NO FERROSOS N.C.P."));
        repository.save(new Giro(273100, "FUNDICIÓN DE HIERRO Y ACERO"));
        repository.save(new Giro(273200, "FUNDICIÓN DE METALES NO FERROSOS"));
        repository.save(new Giro(281100, "FABRICACIÓN DE PRODUCTOS METÁLICOS DE USO ESTRUCTURAL"));
        repository.save(new Giro(281211, "FABRICACIÓN DE RECIPIENTES DE GAS COMPRIMIDO O LICUADO"));
        repository.save(new Giro(281219, "FABRICACIÓN DE TANQUES"));
        repository.save(new Giro(281280, "REPARACIÓN DE TANQUES"));
        repository.save(new Giro(281310, "FABRICACIÓN DE GENERADORES DE VAPOR"));
        repository.save(new Giro(281380, "REPARACIÓN DE GENERADORES DE VAPOR"));
        repository.save(new Giro(289100, "FORJA, PRENSADO, ESTAMPADO Y LAMINADO DE METAL, INCLUYE PULVIMETALURGIA"));
        repository.save(new Giro(289200, "TRATAMIENTOS Y REVESTIMIENTOS DE METALES, OBRAS DE INGENIERÍA MECÁNICA EN GENERAL"));
        repository.save(new Giro(289310, "FABRICACIÓN DE ARTÍCULOS DE CUCHILLERÍA"));
        repository.save(new Giro(289320, "FABRICACIÓN DE HERRAMIENTAS DE MANO Y ARTÍCULOS DE FERRETERÍA"));
        repository.save(new Giro(289910, "FABRICACIÓN DE CABLES"));
        repository.save(new Giro(289990, "FABRICACIÓN DE OTROS PRODUCTOS ELABORADOS DE METAL N.C.P."));
        repository.save(new Giro(291110, "FABRICACIÓN DE MOTORES Y TURBINAS"));
        repository.save(new Giro(291180, "REPARACIÓN DE MOTORES Y TURBINAS"));
        repository.save(new Giro(291210, "FABRICACIÓN DE BOMBAS"));
        repository.save(new Giro(291280, "REPARACIÓN DE BOMBAS"));
        repository.save(new Giro(291310, "FABRICACIÓN DE COJINETES"));
        repository.save(new Giro(291380, "REPARACIÓN DE COJINETES"));
        repository.save(new Giro(291410, "FABRICACIÓN DE HORNOS"));
        repository.save(new Giro(291480, "REPARACIÓN DE HORNOS"));
        repository.save(new Giro(291510, "FABRICACIÓN DE EQUIPO DE ELEVACIÓN Y MANIPULACIÓN"));
        repository.save(new Giro(291580, "REPARACIÓN DE EQUIPO DE ELEVACIÓN Y MANIPULACIÓN"));
        repository.save(new Giro(291910, "FABRICACIÓN DE OTRO TIPO DE MAQUINARIAS DE USO GENERAL"));
        repository.save(new Giro(291980, "REPARACIÓN OTROS TIPOS DE MAQUINARIA Y EQUIPOS DE USO GENERAL"));
        repository.save(new Giro(292110, "FABRICACIÓN DE MAQUINARIA AGROPECUARIA Y FORESTAL"));
        repository.save(new Giro(292180, "REPARACIÓN DE MAQUINARIA AGROPECUARIA Y FORESTAL"));
        repository.save(new Giro(292210, "FABRICACIÓN DE MÁQUINAS HERRAMIENTAS"));
        repository.save(new Giro(292280, "REPARACIÓN DE MÁQUINAS HERRAMIENTAS"));
        repository.save(new Giro(292310, "FABRICACIÓN DE MAQUINARIA METALÚRGICA"));
        repository.save(new Giro(292380, "REPARACIÓN DE MAQUINARIA PARA LA INDUSTRIA METALÚRGICA"));
        repository.save(new Giro(292411, "FABRICACIÓN DE MAQUINARIA PARA MINAS Y CANTERAS Y PARA OBRAS DE CONSTRUCCIÓN"));
        repository.save(new Giro(292412, "FABRICACIÓN DE PARTES PARA MÁQUINAS DE SONDEO O PERFORACIÓN"));
        repository.save(new Giro(292480, "REPARACIÓN DE MAQUINARIA PARA LA EXPLOTACIÓN DE PETRÓLEO"));
        repository.save(new Giro(292510, "FABRICACIÓN DE MAQUINARIA PARA LA ELABORACIÓN DE ALIMENTOS"));
        repository.save(new Giro(292580, "REPARACIÓN DE MAQUINARIA PARA LA ELABORACIÓN DE ALIMENTOS"));
        repository.save(new Giro(292610, "FABRICACIÓN DE MAQUINARIA PARA LA ELABORACIÓN DE PRENDAS TEXTILES"));
        repository.save(new Giro(292680, "REPARACIÓN DE MAQUINARIA PARA LA INDUSTRIA TEXTIL"));
        repository.save(new Giro(292710, "FABRICACIÓN DE ARMAS Y MUNICIONES"));
        repository.save(new Giro(292780, "REPARACIÓN DE ARMAS"));
        repository.save(new Giro(292910, "FABRICACIÓN DE OTROS TIPOS DE MAQUINARIAS DE USO ESPECIAL"));
        repository.save(new Giro(292980, "REPARACIÓN DE OTROS TIPOS DE MAQUINARIA DE USO ESPECIAL"));
        repository.save(new Giro(293000, "FABRICACIÓN DE APARATOS DE USO DOMÉSTICO N.C.P."));
        repository.save(new Giro(300010, "FABRICACIÓN Y ARMADO DE COMPUTADORES Y HARDWARE EN GENERAL"));
        repository.save(new Giro(300020, "FABRICACIÓN DE MAQUINARIA DE OFICINA"));
        repository.save(new Giro(311010, "FABRICACIÓN DE MOTORES"));
        repository.save(new Giro(311080, "REPARACIÓN DE MOTORES"));
        repository.save(new Giro(312010, "FABRICACIÓN DE APARATOS DE DISTRIBUCIÓN Y CONTROL"));
        repository.save(new Giro(312080, "REPARACIÓN DE APARATOS DE DISTRIBUCIÓN Y CONTROL"));
        repository.save(new Giro(313000, "FABRICACIÓN DE HILOS Y CABLES AISLADOS"));
        repository.save(new Giro(314000, "FABRICACIÓN DE ACUMULADORES DE PILAS Y BATERÍAS PRIMARIAS"));
        repository.save(new Giro(315010, "FABRICACIÓN DE LÁMPARAS Y EQUIPO DE ILUMINACIÓN"));
        repository.save(new Giro(315080, "REPARACIÓN DE EQUIPO DE ILUMINACIÓN"));
        repository.save(new Giro(319010, "FABRICACIÓN DE OTROS TIPOS DE EQUIPO ELÉCTRICO N.C.P."));
        repository.save(new Giro(319080, "REPARACIÓN DE OTROS TIPOS DE EQUIPO ELÉCTRICO N.C.P."));
        repository.save(new Giro(321010, "FABRICACIÓN DE COMPONENTES ELECTRÓNICOS"));
        repository.save(new Giro(321080, "REPARACIÓN DE COMPONENTES ELECTRÓNICOS"));
        repository.save(new Giro(322010, "FABRICACIÓN DE TRANSMISORES DE RADIO Y TELEVISIÓN"));
        repository.save(new Giro(322080, "REPARACIÓN DE TRANSMISORES DE RADIO Y TELEVISIÓN"));
        repository.save(new Giro(323000, "FABRICACIÓN DE RECEPTORES (RADIO Y TV), APARATOS DE GRABACIÓN Y REPRODUCCIÓN (AUDIO Y VIDEO)"));
        repository.save(new Giro(331110, "FABRICACIÓN DE EQUIPO MÉDICO Y QUIRÚRGICO"));
        repository.save(new Giro(331120, "LABORATORIOS DENTALES"));
        repository.save(new Giro(331180, "REPARACIÓN DE EQUIPO MÉDICO Y QUIRÚRGICO"));
        repository.save(new Giro(331210, "FABRICACIÓN DE INSTRUMENTOS Y APARATOS PARA MEDIR"));
        repository.save(new Giro(331280, "REPARACIÓN DE INSTRUMENTOS Y APARATOS PARA MEDIR"));
        repository.save(new Giro(331310, "FABRICACIÓN DE EQUIPOS DE CONTROL DE PROCESOS INDUSTRIALES"));
        repository.save(new Giro(331380, "REPARACIÓN DE EQUIPOS DE CONTROL DE PROCESOS INDUSTRIALES"));
        repository.save(new Giro(332010, "FABRICACIÓN Y/O REPARACIÓN DE LENTES Y ARTÍCULOS OFTALMOLÓGICOS"));
        repository.save(new Giro(332020, "FABRICACIÓN DE INSTRUMENTOS DE OPTICA N.C.P. Y EQUIPOS FOTOGRÁFICOS"));
        repository.save(new Giro(332080, "REPARACIÓN DE INSTRUMENTOS DE OPTICA N.C.P Y EQUIPO FOTOGRÁFICOS"));
        repository.save(new Giro(333000, "FABRICACIÓN DE RELOJES"));
        repository.save(new Giro(341000, "FABRICACIÓN DE VEHÍCULOS AUTOMOTORES"));
        repository.save(new Giro(342000, "FABRICACIÓN DE CARROCERÍAS PARA VEHÍCULOS AUTOMOTORES, FABRICACIÓN DE REMOLQUES Y SEMI REMOLQUES"));
        repository.save(new Giro(343000, "FABRICACIÓN DE PARTES Y ACCESORIOS PARA VEHÍCULOS AUTOMOTORES Y SUS MOTORES"));
        repository.save(new Giro(351110, "CONSTRUCCIÓN Y REPARACIÓN DE BUQUES, ASTILLEROS"));
        repository.save(new Giro(351120, "CONSTRUCCIÓN DE EMBARCACIONES MENORES"));
        repository.save(new Giro(351180, "REPARACIÓN DE EMBARCACIONES MENORES"));
        repository.save(new Giro(351210, "CONSTRUCCIÓN DE EMBARCACIONES DE RECREO Y DEPORTE"));
        repository.save(new Giro(351280, "REPARACIÓN DE EMBARCACIONES DE RECREO Y DEPORTES"));
        repository.save(new Giro(352000, "FABRICACIÓN DE LOCOMOTORAS Y DE MATERIAL RODANTE PARA FERROCARRILES Y TRANVÍAS"));
        repository.save(new Giro(353010, "FABRICACIÓN DE AERONAVES Y NAVES ESPACIALES"));
        repository.save(new Giro(353080, "REPARACIÓN DE AERONAVES Y NAVES ESPACIALES"));
        repository.save(new Giro(359100, "FABRICACIÓN DE MOTOCICLETAS"));
        repository.save(new Giro(359200, "FABRICACIÓN DE BICICLETAS Y DE SILLONES DE RUEDAS PARA INVALIDOS"));
        repository.save(new Giro(359900, "FABRICACIÓN DE OTROS EQUIPOS DE TRANSPORTE N.C.P."));
        repository.save(new Giro(361010, "FABRICACIÓN DE MUEBLES PRINCIPALMENTE DE MADERA"));
        repository.save(new Giro(361020, "FABRICACIÓN DE OTROS MUEBLES N.C.P."));
        repository.save(new Giro(369100, "FABRICACIÓN DE JOYAS Y PRODUCTOS CONEXOS"));
        repository.save(new Giro(369200, "FABRICACIÓN DE INSTRUMENTOS DE MÚSICA"));
        repository.save(new Giro(369300, "FABRICACIÓN DE ARTÍCULOS DE DEPORTE"));
        repository.save(new Giro(369400, "FABRICACIÓN DE JUEGOS Y JUGUETES"));
        repository.save(new Giro(369910, "FABRICACIÓN DE PLUMAS Y LÁPICES DE TODA CLASE Y ARTÍCULOS DE ESCRITORIO EN GENERAL"));
        repository.save(new Giro(369920, "FABRICACIÓN DE BROCHAS"));
        repository.save(new Giro(369930, "FABRICACIÓN DE FÓSFOROS"));
        repository.save(new Giro(369990, "FABRICACIÓN DE ARTÍCULOS DE OTRAS INDUSTRIAS N.C.P."));
        repository.save(new Giro(371000, "RECICLAMIENTO DE DESPERDICIOS Y DESECHOS METÁLICOS"));
        repository.save(new Giro(372010, "RECICLAMIENTO DE PAPEL"));
        repository.save(new Giro(372020, "RECICLAMIENTO DE VIDRIO"));
        repository.save(new Giro(372090, "RECICLAMIENTO DE OTROS DESPERDICIOS Y DESECHOS N.C.P."));
        repository.save(new Giro(401011, "GENERACIÓN HIDROELÉCTRICA"));
        repository.save(new Giro(401012, "GENERACIÓN EN CENTRALES TERMOELÉCTRICA DE CICLOS COMBINADOS"));
        repository.save(new Giro(401013, "GENERACIÓN EN OTRAS CENTRALES TERMOELÉCTRICAS"));
        repository.save(new Giro(401019, "GENERACIÓN EN OTRAS CENTRALES N.C.P."));
        repository.save(new Giro(401020, "TRANSMISIÓN DE ENERGÍA ELÉCTRICA"));
        repository.save(new Giro(401030, "DISTRIBUCIÓN DE ENERGIA ELÉCTRICA"));
        repository.save(new Giro(402000, "FABRICACIÓN DE GAS, DISTRIBUCIÓN DE COMBUSTIBLES GASEOSOS POR TUBERÍAS"));
        repository.save(new Giro(403000, "SUMINISTRO DE VAPOR Y AGUA CALIENTE"));
        repository.save(new Giro(410000, "CAPTACIÓN"));
        repository.save(new Giro(451010, "PREPARACIÓN DEL TERRENO"));
        repository.save(new Giro(451020, "SERVICIOS DE DEMOLICIÓN Y EL DERRIBO DE EDIFICIOS Y OTRAS ESTRUCTURAS"));
        repository.save(new Giro(452010, "CONSTRUCCIÓN DE EDIFICIOS COMPLETOS O DE PARTES DE EDIFICIOS"));
        repository.save(new Giro(452020, "OBRAS DE INGENIERÍA"));
        repository.save(new Giro(453000, "ACONDICIONAMIENTO DE EDIFICIOS"));
        repository.save(new Giro(454000, "OBRAS MENORES EN CONSTRUCCIÓN (CONTRATISTAS"));
        repository.save(new Giro(455000, "ALQUILER DE EQUIPO DE CONSTRUCCIÓN O DEMOLICIÓN DOTADO DE OPERARIOS"));
        repository.save(new Giro(501010, "VENTA AL POR MAYOR DE VEHÍCULOS AUTOMOTORES (IMPORTACIÓN"));
        repository.save(new Giro(501020, "VENTA O COMPRAVENTA AL POR MENOR DE VEHÍCULOS AUTOMOTORES NUEVOS O USADOS, EXCEPTO MOTOCICLETAS"));
        repository.save(new Giro(502010, "SERVICIO DE LAVADO DE VEHÍCULOS AUTOMOTORES"));
        repository.save(new Giro(502020, "SERVICIOS DE REMOLQUE DE VEHÍCULOS (GRUAS)"));
        repository.save(new Giro(502080, "MANTENIMIENTO Y REPARACIÓN DE VEHÍCULOS AUTOMOTORES"));
        repository.save(new Giro(503000, "VENTA DE PARTES"));
        repository.save(new Giro(504010, "VENTA DE MOTOCICLETAS"));
        repository.save(new Giro(504020, "VENTA DE PIEZAS Y ACCESORIOS DE MOTOCICLETAS"));
        repository.save(new Giro(504080, "REPARACIÓN DE MOTOCICLETAS"));
        repository.save(new Giro(505000, "VENTA AL POR MENOR DE COMBUSTIBLE PARA AUTOMOTORES"));
        repository.save(new Giro(511010, "CORRETAJE DE PRODUCTOS AGRÍCOLAS"));
        repository.save(new Giro(511020, "CORRETAJE DE GANADO (FERIAS DE GANADO)"));
        repository.save(new Giro(511030, "OTROS TIPOS DE CORRETAJES O REMATES N.C.P. (NO INCLUYE SERVICIOS DE MARTILLERO)"));
        repository.save(new Giro(512110, "VENTA AL POR MAYOR DE ANIMALES VIVOS"));
        repository.save(new Giro(512120, "VENTA AL POR MAYOR DE PRODUCTOS PECUARIOS (LANAS, PIELES, CUEROS SIN PROCESAR), EXCEPTO ALIMENTOS"));
        repository.save(new Giro(512130, "VENTA AL POR MAYOR DE MATERIAS PRIMAS AGRÍCOLAS"));
        repository.save(new Giro(512210, "MAYORISTA DE FRUTAS Y VERDURAS"));
        repository.save(new Giro(512220, "MAYORISTAS DE CARNES"));
        repository.save(new Giro(512230, "MAYORISTAS DE PRODUCTOS DEL MAR (PESCADO"));
        repository.save(new Giro(512240, "MAYORISTAS DE VINOS Y BEBIDAS ALCOHÓLICAS Y DE FANTASÍA"));
        repository.save(new Giro(512250, "VENTA AL POR MAYOR DE CONFITES"));
        repository.save(new Giro(512260, "VENTA AL POR MAYOR DE TABACO Y PRODUCTOS DERIVADOS"));
        repository.save(new Giro(512290, "VENTA AL POR MAYOR DE HUEVOS"));
        repository.save(new Giro(513100, "VENTA AL POR MAYOR DE PRODUCTOS TEXTILES"));
        repository.save(new Giro(513910, "VENTA AL POR MAYOR DE MUEBLES"));
        repository.save(new Giro(513920, "VENTA AL POR MAYOR DE ARTÍCULOS ELÉCTRICOS Y ELECTRÓNICOS PARA EL HOGAR"));
        repository.save(new Giro(513930, "VENTA AL POR MAYOR DE ARTÍCULOS DE PERFUMERÍA"));
        repository.save(new Giro(513940, "VENTA AL POR MAYOR DE PAPEL Y CARTÓN"));
        repository.save(new Giro(513951, "VENTA AL POR MAYOR DE LIBROS"));
        repository.save(new Giro(513952, "VENTA AL POR MAYOR DE REVISTAS Y PERIÓDICOS"));
        repository.save(new Giro(513960, "VENTA AL POR MAYOR DE PRODUCTOS FARMACEUTICOS"));
        repository.save(new Giro(513970, "VENTA AL POR MAYOR DE INSTRUMENTOS CIENTÍFICOS Y QUIRÚRGICOS"));
        repository.save(new Giro(513990, "VENTA AL POR MAYOR DE OTROS ENSERES DOMÉSTICOS N.C.P."));
        repository.save(new Giro(514110, "VENTA AL POR MAYOR DE COMBUSTIBLES LÍQUIDOS"));
        repository.save(new Giro(514120, "VENTA AL POR MAYOR DE COMBUSTIBLES SÓLIDOS"));
        repository.save(new Giro(514130, "VENTA AL POR MAYOR DE COMBUSTIBLES GASEOSOS"));
        repository.save(new Giro(514140, "VENTA AL POR MAYOR DE PRODUCTOS CONEXOS A LOS COMBUSTIBLES"));
        repository.save(new Giro(514200, "VENTA AL POR MAYOR DE METALES Y MINERALES METALÍFEROS"));
        repository.save(new Giro(514310, "VENTA AL POR MAYOR DE MADERA NO TRABAJADA Y PRODUCTOS RESULTANTES DE SU ELABORACIÓN PRIMARIA"));
        repository.save(new Giro(514320, "VENTA AL POR MAYOR DE MATERIALES DE CONSTRUCCIÓN"));
        repository.save(new Giro(514910, "VENTA AL POR MAYOR DE PRODUCTOS QUÍMICOS"));
        repository.save(new Giro(514920, "VENTA AL POR MAYOR DE DESECHOS METÁLICOS (CHATARRA)"));
        repository.save(new Giro(514930, "VENTA AL POR MAYOR DE INSUMOS VETERINARIOS"));
        repository.save(new Giro(514990, "VENTA AL POR MAYOR DE OTROS PRODUCTOS INTERMEDIOS"));
        repository.save(new Giro(515001, "VENTA AL POR MAYOR DE MAQUINARIA AGRÍCOLA Y FORESTAL"));
        repository.save(new Giro(515002, "VENTA AL POR MAYOR DE MAQUINARIA METALÚRGICA"));
        repository.save(new Giro(515003, "VENTA AL POR MAYOR DE MAQUINARIA PARA LA MINERÍA"));
        repository.save(new Giro(515004, "VENTA AL POR MAYOR DE MAQUINARIA PARA LA CONSTRUCCIÓN"));
        repository.save(new Giro(515005, "VENTA AL POR MAYOR DE MAQUINARIA PARA LA ELABORACIÓN DE ALIMENTOS"));
        repository.save(new Giro(515006, "VENTA AL POR MAYOR DE MAQUINARIA PARA TEXTILES Y CUEROS"));
        repository.save(new Giro(515007, "VENTA AL POR MAYOR DE MÁQUINAS Y EQUIPOS DE OFICINA, INCLUYE MATERIALES CONEXOS"));
        repository.save(new Giro(515008, "VENTA AL POR MAYOR DE MAQUINARIA Y EQUIPO DE TRANSPORTE EXCEPTO VEHÍCULOS AUTOMOTORES"));
        repository.save(new Giro(515009, "VENTA AL POR MAYOR DE MAQUINARIA"));
        repository.save(new Giro(519000, "VENTA AL POR MAYOR DE OTROS PRODUCTOS N.C.P."));
        repository.save(new Giro(521111, "GRANDES ESTABLECIMIENTOS (VENTA DE ALIMENTOS), HIPERMERCADOS"));
        repository.save(new Giro(521112, "ALMACENES MEDIANOS (VENTA DE ALIMENTOS), SUPERMERCADOS, MINIMARKETS"));
        repository.save(new Giro(521120, "ALMACENES PEQUENOS (VENTA DE ALIMENTOS)"));
        repository.save(new Giro(521200, "GRANDES TIENDAS - PRODUCTOS DE FERRETERÍA Y PARA EL HOGAR"));
        repository.save(new Giro(521300, "GRANDES TIENDAS - VESTUARIO Y PRODUCTOS PARA EL HOGAR"));
        repository.save(new Giro(521900, "VENTA AL POR MENOR DE OTROS PRODUCTOS EN PEQUENOS ALMACENES NO ESPECIALIZADOS"));
        repository.save(new Giro(522010, "VENTA AL POR MENOR DE BEBIDAS Y LICORES (BOTILLERÍAS)"));
        repository.save(new Giro(522020, "VENTA AL POR MENOR DE CARNES (ROJAS"));
        repository.save(new Giro(522030, "COMERCIO AL POR MENOR DE VERDURAS Y FRUTAS (VERDULERÍA)"));
        repository.save(new Giro(522040, "VENTA AL POR MENOR DE PESCADOS"));
        repository.save(new Giro(522050, "VENTA AL POR MENOR DE PRODUCTOS DE PANADERÍA Y PASTELERÍA"));
        repository.save(new Giro(522060, "VENTA AL POR MENOR DE ALIMENTOS PARA MASCOTAS Y ANIMALES EN GENERAL"));
        repository.save(new Giro(522070, "VENTA AL POR MENOR DE AVES Y HUEVOS"));
        repository.save(new Giro(522090, "VENTA AL POR MENOR DE PRODUCTOS DE CONFITERÍAS"));
        repository.save(new Giro(523111, "FARMACIAS - PERTENECIENTES A CADENA DE ESTABLECIMIENTOS"));
        repository.save(new Giro(523112, "FARMACIAS INDEPENDIENTES"));
        repository.save(new Giro(523120, "VENTA AL POR MENOR DE PRODUCTOS MEDICINALES"));
        repository.save(new Giro(523130, "VENTA AL POR MENOR DE ARTÍCULOS ORTOPÉDICOS"));
        repository.save(new Giro(523140, "VENTA AL POR MENOR DE ARTÍCULOS DE TOCADOR Y COSMÉTICOS"));
        repository.save(new Giro(523210, "VENTA AL POR MENOR DE CALZADO"));
        repository.save(new Giro(523220, "VENTA AL POR MENOR DE PRENDAS DE VESTIR EN GENERAL"));
        repository.save(new Giro(523230, "VENTA AL POR MENOR DE LANAS"));
        repository.save(new Giro(523240, "VENTA AL POR MENOR DE MALETERÍAS"));
        repository.save(new Giro(523250, "VENTA AL POR MENOR DE ROPA INTERIOR Y PRENDAS DE USO PERSONAL"));
        repository.save(new Giro(523290, "COMERCIO AL POR MENOR DE TEXTILES PARA EL HOGAR Y OTROS PRODUCTOS TEXTILES N.C.P."));
        repository.save(new Giro(523310, "VENTA AL POR MENOR DE ARTÍCULOS ELECTRODOMÉSTICOS Y ELECTRÓNICOS PARA EL HOGAR"));
        repository.save(new Giro(523320, "VENTA AL POR MENOR DE CRISTALES"));
        repository.save(new Giro(523330, "VENTA AL POR MENOR DE MUEBLES, INCLUYE COLCHONES"));
        repository.save(new Giro(523340, "VENTA AL POR MENOR DE INSTRUMENTOS MUSICALES (CASA DE MÚSICA)"));
        repository.save(new Giro(523350, "VENTA AL POR MENOR DE DISCOS"));
        repository.save(new Giro(523360, "VENTA AL POR MENOR DE LÁMPARAS"));
        repository.save(new Giro(523390, "VENTA AL POR MENOR DE APARATOS"));
        repository.save(new Giro(523410, "VENTA AL POR MENOR DE ARTÍCULOS DE FERRETERÍA Y MATERIALES DE CONSTRUCCIÓN"));
        repository.save(new Giro(523420, "VENTA AL POR MENOR DE PINTURAS"));
        repository.save(new Giro(523430, "COMERCIO AL POR MENOR DE PRODUCTOS DE VIDRIO"));
        repository.save(new Giro(523911, "COMERCIO AL POR MENOR DE ARTÍCULOS FOTOGRÁFICOS"));
        repository.save(new Giro(523912, "COMERCIO AL POR MENOR DE ARTÍCULOS ÓPTICOS"));
        repository.save(new Giro(523921, "COMERCIO POR MENOR DE JUGUETES"));
        repository.save(new Giro(523922, "COMERCIO AL POR MENOR DE LIBROS"));
        repository.save(new Giro(523923, "COMERCIO AL POR MENOR DE REVISTAS Y DIARIOS"));
        repository.save(new Giro(523924, "COMERCIO DE ARTÍCULOS DE SUMINISTROS DE OFICINAS Y ARTÍCULOS DE ESCRITORIO EN GENERAL"));
        repository.save(new Giro(523930, "COMERCIO AL POR MENOR DE COMPUTADORAS"));
        repository.save(new Giro(523941, "COMERCIO AL POR MENOR DE ARMERÍAS"));
        repository.save(new Giro(523942, "COMERCIO AL POR MENOR DE BICICLETAS Y SUS REPUESTOS"));
        repository.save(new Giro(523943, "COMERCIO AL POR MENOR DE ARTÍCULOS DEPORTIVOS"));
        repository.save(new Giro(523950, "COMERCIO AL POR MENOR DE ARTÍCULOS DE JOYERÍA"));
        repository.save(new Giro(523961, "VENTA AL POR MENOR DE GAS LICUADO EN BOMBONAS"));
        repository.save(new Giro(523969, "VENTA AL POR MENOR DE CARBÓN"));
        repository.save(new Giro(523991, "COMERCIO AL POR MENOR DE ARTÍCULOS TÍPICOS (ARTESANÍAS)"));
        repository.save(new Giro(523992, "VENTA AL POR MENOR DE FLORES"));
        repository.save(new Giro(523993, "VENTA AL POR MENOR DE MASCOTAS Y ACCESORIOS"));
        repository.save(new Giro(523999, "VENTAS AL POR MENOR DE OTROS PRODUCTOS EN ALMACENES ESPECIALIZADOS N.C.P."));
        repository.save(new Giro(524010, "COMERCIO AL POR MENOR DE ANTIGUEDADES"));
        repository.save(new Giro(524020, "COMERCIO AL POR MENOR DE ROPA USADA"));
        repository.save(new Giro(524090, "COMERCIO AL POR MENOR DE ARTÍCULOS Y ARTEFACTOS USADOS N.C.P."));
        repository.save(new Giro(525110, "VENTA AL POR MENOR EN EMPRESAS DE VENTA A DISTANCIA POR CORREO"));
        repository.save(new Giro(525120, "VENTA AL POR MENOR EN EMPRESAS DE VENTA A DISTANCIA VÍA TELEFÓNICA"));
        repository.save(new Giro(525130, "VENTA AL POR MENOR EN EMPRESAS DE VENTA A DISTANCIA VÍA INTERNET, COMERCIO ELECTRÓNICO"));
        repository.save(new Giro(525200, "VENTA AL POR MENOR EN PUESTOS DE VENTA Y MERCADOS"));
        repository.save(new Giro(525911, "VENTA AL POR MENOR REALIZADA POR INDEPENDIENTES EN TRANSPORTE PÚBLICO (LEY 20.388)"));
        repository.save(new Giro(525919, "VENTA AL POR MENOR NO REALIZADA EN ALMACENES DE PRODUCTOS PROPIOS N.C.P."));
        repository.save(new Giro(525920, "MÁQUINAS EXPENDEDORAS"));
        repository.save(new Giro(525930, "VENTA AL POR MENOR A CAMBIO DE UNA RETRIBUCIÓN O POR CONTRATA"));
        repository.save(new Giro(525990, "OTROS TIPOS DE VENTA AL POR MENOR NO REALIZADA EN ALMACENES N.C.P."));
        repository.save(new Giro(526010, "REPARACIÓN DE CALZADO Y OTROS ARTÍCULOS DE CUERO"));
        repository.save(new Giro(526020, "REPARACIONES ELÉCTRICAS Y ELECTRÓNICAS"));
        repository.save(new Giro(526030, "REPARACIÓN DE RELOJES Y JOYAS"));
        repository.save(new Giro(526090, "OTRAS REPARACIONES DE EFECTOS PERSONALES Y ENSERES DOMÉSTICOS N.C.P."));
        repository.save(new Giro(551010, "HOTELES"));
        repository.save(new Giro(551020, "MOTELES"));
        repository.save(new Giro(551030, "RESIDENCIALES"));
        repository.save(new Giro(551090, "OTROS TIPOS DE HOSPEDAJE TEMPORAL COMO CAMPING"));
        repository.save(new Giro(552010, "RESTAURANTES"));
        repository.save(new Giro(552020, "ESTABLECIMIENTOS DE COMIDA RÁPIDA (BARES"));
        repository.save(new Giro(552030, "CASINOS Y CLUBES SOCIALES"));
        repository.save(new Giro(552040, "SERVICIOS DE COMIDA PREPARADA EN FORMA INDUSTRIAL"));
        repository.save(new Giro(552050, "SERVICIOS DE BANQUETES"));
        repository.save(new Giro(552090, "SERVICIOS DE OTROS ESTABLECIMIENTOS QUE EXPENDEN COMIDAS Y BEBIDAS"));
        repository.save(new Giro(601001, "TRANSPORTE INTERURBANO DE PASAJEROS POR FERROCARRILES"));
        repository.save(new Giro(601002, "TRANSPORTE DE CARGA POR FERROCARRILES"));
        repository.save(new Giro(602110, "TRANSPORTE URBANO DE PASAJEROS VÍA FERROCARRIL (INCLUYE METRO)"));
        repository.save(new Giro(602120, "TRANSPORTE URBANO DE PASAJEROS VÍA AUTOBUS (LOCOMOCIÓN COLECTIVA)"));
        repository.save(new Giro(602130, "TRANSPORTE INTERURBANO DE PASAJEROS VÍA AUTOBUS"));
        repository.save(new Giro(602140, "TRANSPORTE URBANO DE PASAJEROS VÍA TAXI COLECTIVO"));
        repository.save(new Giro(602150, "SERVICIOS DE TRANSPORTE ESCOLAR"));
        repository.save(new Giro(602160, "SERVICIOS DE TRANSPORTE DE TRABAJADORES"));
        repository.save(new Giro(602190, "OTROS TIPOS DE TRANSPORTE REGULAR DE PASAJEROS POR VÍA TERRESTRE N.C.P."));
        repository.save(new Giro(602210, "TRANSPORTES POR TAXIS LIBRES Y RADIOTAXIS"));
        repository.save(new Giro(602220, "SERVICIOS DE TRANSPORTE A TURISTAS"));
        repository.save(new Giro(602230, "TRANSPORTE DE PASAJEROS EN VEHÍCULOS DE TRACCIÓN HUMANA Y ANIMAL"));
        repository.save(new Giro(602290, "OTROS TIPOS DE TRANSPORTE NO REGULAR DE PASAJEROS N.C.P."));
        repository.save(new Giro(602300, "TRANSPORTE DE CARGA POR CARRETERA"));
        repository.save(new Giro(603000, "TRANSPORTE POR TUBERÍAS"));
        repository.save(new Giro(611001, "TRANSPORTE MARÍTIMO Y DE CABOTAJE DE PASAJEROS"));
        repository.save(new Giro(611002, "TRANSPORTE MARÍTIMO Y DE CABOTAJE DE CARGA"));
        repository.save(new Giro(612001, "TRANSPORTE DE PASAJEROS POR VÍAS DE NAVEGACIÓN INTERIORES"));
        repository.save(new Giro(612002, "TRANSPORTE DE CARGA POR VÍAS DE NAVEGACIÓN INTERIORES"));
        repository.save(new Giro(621010, "TRANSPORTE REGULAR POR VÍA AÉREA DE PASAJEROS"));
        repository.save(new Giro(621020, "TRANSPORTE REGULAR POR VÍA AÉREA DE CARGA"));
        repository.save(new Giro(622001, "TRANSPORTE NO REGULAR POR VÍA AÉREA DE PASAJEROS"));
        repository.save(new Giro(622002, "TRANSPORTE NO REGULAR POR VÍA AÉREA DE CARGA"));
        repository.save(new Giro(630100, "MANIPULACIÓN DE LA CARGA"));
        repository.save(new Giro(630200, "SERVICIOS DE ALMACENAMIENTO Y DEPÓSITO"));
        repository.save(new Giro(630310, "TERMINALES TERRESTRES DE PASAJEROS"));
        repository.save(new Giro(630320, "ESTACIONAMIENTO DE VEHÍCULOS Y PARQUÍMETROS"));
        repository.save(new Giro(630330, "PUERTOS Y AEROPUERTOS"));
        repository.save(new Giro(630340, "SERVICIOS PRESTADOS POR CONCESIONARIOS DE CARRETERAS"));
        repository.save(new Giro(630390, "OTRAS ACTIVIDADES CONEXAS AL TRANSPORTE N.C.P."));
        repository.save(new Giro(630400, "AGENCIAS Y ORGANIZADORES DE VIAJES, ACTIVIDADES DE ASISTENCIA A TURISTAS N.C.P."));
        repository.save(new Giro(630910, "AGENCIAS DE ADUANAS"));
        repository.save(new Giro(630920, "AGENCIAS DE TRANSPORTE"));
        repository.save(new Giro(641100, "ACTIVIDADES POSTALES NACIONALES"));
        repository.save(new Giro(641200, "ACTIVIDADES DE CORREO DISTINTAS DE LAS ACTIVIDADES POSTALES NACIONALES"));
        repository.save(new Giro(642010, "SERVICIOS DE TELEFONÍA FIJA"));
        repository.save(new Giro(642020, "SERVICIOS DE TELEFONÍA MÓVIL"));
        repository.save(new Giro(642030, "PORTADORES TELEFÓNICOS (LARGA DISTANCIA NACIONAL E INTERNACIONAL)"));
        repository.save(new Giro(642040, "SERVICIOS DE TELEVISIÓN NO ABIERTA"));
        repository.save(new Giro(642050, "PROVEEDORES DE INTERNET"));
        repository.save(new Giro(642061, "CENTROS DE LLAMADOS, INCLUYE ENVÍO DE FAX"));
        repository.save(new Giro(642062, "CENTROS DE ACCESO A INTERNET"));
        repository.save(new Giro(642090, "OTROS SERVICIOS DE TELECOMUNICACIONES N.C.P."));
        repository.save(new Giro(651100, "BANCA CENTRAL"));
        repository.save(new Giro(651910, "BANCOS"));
        repository.save(new Giro(651920, "FINANCIERAS"));
        repository.save(new Giro(651990, "OTROS TIPOS DE INTERMEDIACIÓN MONETARIA N.C.P."));
        repository.save(new Giro(659110, "LEASING FINANCIERO"));
        repository.save(new Giro(659120, "LEASING HABITACIONAL"));
        repository.save(new Giro(659210, "FINANCIAMIENTO DEL FOMENTO DE LA PRODUCCIÓN"));
        repository.save(new Giro(659220, "ACTIVIDADES DE CRÉDITO PRENDARIO"));
        repository.save(new Giro(659231, "FACTORING"));
        repository.save(new Giro(659232, "SECURITIZADORAS"));
        repository.save(new Giro(659290, "OTROS INSTITUCIONES FINANCIERAS N.C.P."));
        repository.save(new Giro(659911, "ADMINISTRADORAS DE FONDOS DE INVERSIÓN"));
        repository.save(new Giro(659912, "ADMINISTRADORAS DE FONDOS MUTUOS"));
        repository.save(new Giro(659913, "ADMINISTRADORAS DE FICES (FONDOS DE INVERSIÓN DE CAPITAL EXTRANJERO)"));
        repository.save(new Giro(659914, "ADMINISTRADORAS DE FONDOS PARA LA VIVIENDA"));
        repository.save(new Giro(659915, "ADMINISTRADORAS DE FONDOS PARA OTROS FINES Y/O GENERALES"));
        repository.save(new Giro(659920, "SOCIEDADES DE INVERSIÓN Y RENTISTAS DE CAPITALES MOBILIARIOS EN GENERAL"));
        repository.save(new Giro(660101, "PLANES DE SEGURO DE VIDA"));
        repository.save(new Giro(660102, "PLANES DE REASEGUROS DE VIDA"));
        repository.save(new Giro(660200, "ADMINISTRADORAS DE FONDOS DE PENSIONES (AFP)"));
        repository.save(new Giro(660301, "PLANES DE SEGUROS GENERALES"));
        repository.save(new Giro(660302, "PLANES DE REASEGUROS GENERALES"));
        repository.save(new Giro(660400, "ISAPRES"));
        repository.save(new Giro(671100, "ADMINISTRACIÓN DE MERCADOS FINANCIEROS"));
        repository.save(new Giro(671210, "CORREDORES DE BOLSA"));
        repository.save(new Giro(671220, "AGENTES DE VALORES"));
        repository.save(new Giro(671290, "OTROS SERVICIOS DE CORRETAJE"));
        repository.save(new Giro(671910, "CÁMARA DE COMPENSACIÓN"));
        repository.save(new Giro(671921, "ADMINISTRADORA DE TARJETAS DE CRÉDITO"));
        repository.save(new Giro(671929, "EMPRESAS DE ASESORÍA"));
        repository.save(new Giro(671930, "CLASIFICADORES DE RIESGOS"));
        repository.save(new Giro(671940, "CASAS DE CAMBIO Y OPERADORES DE DIVISA"));
        repository.save(new Giro(671990, "OTRAS ACTIVIDADES AUXILIARES DE LA INTERMEDIACIÓN FINANCIERA N.C.P."));
        repository.save(new Giro(672010, "CORREDORES DE SEGUROS"));
        repository.save(new Giro(672020, "AGENTES Y LIQUIDADORES DE SEGUROS"));
        repository.save(new Giro(672090, "OTRAS ACTIVIDADES AUXILIARES DE LA FINANCIACIÓN DE PLANES DE SEGUROS Y DE PENSIONES N.C.P."));
        repository.save(new Giro(701001, "ARRIENDO DE INMUEBLES AMOBLADOS O CON EQUIPOS Y MAQUINARIAS"));
        repository.save(new Giro(701009, "COMPRA"));
        repository.save(new Giro(702000, "CORREDORES DE PROPIEDADES"));
        repository.save(new Giro(711101, "ALQUILER DE AUTOS Y CAMIONETAS SIN CHOFER"));
        repository.save(new Giro(711102, "ALQUILER DE OTROS EQUIPOS DE TRANSPORTE POR VÍA TERRESTRE SIN OPERARIOS"));
        repository.save(new Giro(711200, "ALQUILER DE TRANSPORTE POR VÍA ACUÁTICA SIN TRIPULACIÓN"));
        repository.save(new Giro(711300, "ALQUILER DE EQUIPO DE TRANSPORTE POR VÍA AÉREA SIN TRIPULANTES"));
        repository.save(new Giro(712100, "ALQUILER DE MAQUINARIA Y EQUIPO AGROPECUARIO"));
        repository.save(new Giro(712200, "ALQUILER DE MAQUINARIA Y EQUIPO DE CONSTRUCCIÓN E INGENIERÍA CIVIL"));
        repository.save(new Giro(712300, "ALQUILER DE MAQUINARIA Y EQUIPO DE OFICINA (SIN OPERARIOS NI SERVICIO ADMINISTRATIVO)"));
        repository.save(new Giro(712900, "ALQUILER DE OTROS TIPOS DE MAQUINARIAS Y EQUIPOS N.C.P."));
        repository.save(new Giro(713010, "ALQUILER DE BICICLETAS Y ARTÍCULOS PARA DEPORTES"));
        repository.save(new Giro(713020, "ARRIENDO DE VIDEOS"));
        repository.save(new Giro(713030, "ALQUILER DE MOBILIARIO PARA EVENTOS (SILLAS"));
        repository.save(new Giro(713090, "ALQUILER DE OTROS EFECTOS PERSONALES Y ENSERES DOMÉSTICOS N.C.P."));
        repository.save(new Giro(722000, "ASESORES Y CONSULTORES EN INFORMÁTICA (SOFTWARE)"));
        repository.save(new Giro(724000, "PROCESAMIENTO DE DATOS Y ACTIVIDADES RELACIONADAS CON BASES DE DATOS"));
        repository.save(new Giro(726000, "EMPRESAS DE SERVICIOS INTEGRALES DE INFORMÁTICA"));
        repository.save(new Giro(725000, "MANTENIMIENTO Y REPARACIÓN DE MAQUINARIA DE OFICINA"));
        repository.save(new Giro(731000, "INVESTIGACIONES Y DESARROLLO EXPERIMENTAL EN EL CAMPO DE LAS CIENCIAS NATURALES Y LA INGENIERÍA"));
        repository.save(new Giro(732000, "INVESTIGACIONES Y DESARROLLO EXPERIMENTAL EN EL CAMPO DE LAS CIENCIAS SOCIALES Y LAS HUMANIDADES"));
        repository.save(new Giro(741110, "SERVICIOS JURÍDICOS"));
        repository.save(new Giro(741120, "SERVICIO NOTARIAL"));
        repository.save(new Giro(741130, "CONSERVADOR DE BIENES RAICES"));
        repository.save(new Giro(741140, "RECEPTORES JUDICIALES"));
        repository.save(new Giro(741190, "ARBITRAJES"));
        repository.save(new Giro(741200, "ACTIVIDADES DE CONTABILIDAD, TENEDURÍA DE LIBROS Y AUDITORÍA, ASESORAMIENTOS TRIBUTARIOS"));
        repository.save(new Giro(741300, "INVESTIGACIÓN DE MERCADOS Y REALIZACIÓN DE ENCUESTAS DE OPINIÓN PÚBLICA"));
        repository.save(new Giro(741400, "ACTIVIDADES DE ASESORAMIENTO EMPRESARIAL Y EN MATERIA DE GESTIÓN"));
        repository.save(new Giro(742110, "SERVICIOS DE ARQUITECTURA Y TÉCNICO RELACIONADO"));
        repository.save(new Giro(742121, "EMPRESAS DE SERVICIOS GEOLÓGICOS Y DE PROSPECCIÓN"));
        repository.save(new Giro(742122, "SERVICIOS PROFESIONALES EN GEOLOGÍA Y PROSPECCIÓN"));
        repository.save(new Giro(742131, "EMPRESAS DE SERVICIOS DE TOPOGRAFÍA Y AGRIMENSURA"));
        repository.save(new Giro(742132, "SERVICIOS PROFESIONALES DE TOPOGRAFÍA Y AGRIMENSURA"));
        repository.save(new Giro(742141, "SERVICIOS DE INGENIERÍA PRESTADOS POR EMPRESAS N.C.P."));
        repository.save(new Giro(742142, "SERVICIOS DE INGENIERÍA PRESTADOS POR PROFESIONALES N.C.P."));
        repository.save(new Giro(742190, "OTROS SERVICIOS DESARROLLADOS POR PROFESIONALES"));
        repository.save(new Giro(742210, "SERVICIO DE REVISIÓN TÉCNICA DE VEHÍCULOS AUTOMOTORES"));
        repository.save(new Giro(742290, "OTROS SERVICIOS DE ENSAYOS Y ANALISIS TÉCNICOS"));
        repository.save(new Giro(743001, "EMPRESAS DE PUBLICIDAD"));
        repository.save(new Giro(743002, "SERVICIOS PERSONALES EN PUBLICIDAD"));
        repository.save(new Giro(749110, "SERVICIOS SUMINISTRO DE PERSONAL, EMPRESAS SERVICIOS TRANSITORIOS"));
        repository.save(new Giro(749190, "SERVICIOS DE RECLUTAMIENTO DE PERSONAL"));
        repository.save(new Giro(749210, "ACTIVIDADES DE INVESTIGACIÓN"));
        repository.save(new Giro(749221, "SERVICIOS INTEGRALES DE SEGURIDAD"));
        repository.save(new Giro(749222, "TRANSPORTE DE VALORES"));
        repository.save(new Giro(749229, "SERVICIOS PERSONALES RELACIONADOS CON SEGURIDAD"));
        repository.save(new Giro(749310, "EMPRESAS DE LIMPIEZA DE EDIFICIOS RESIDENCIALES Y NO RESIDENCIALES"));
        repository.save(new Giro(749320, "DESRATIZACIÓN Y FUMIGACIÓN NO AGRÍCOLA"));
        repository.save(new Giro(749401, "SERVICIOS DE REVELADO"));
        repository.save(new Giro(749402, "ACTIVIDADES DE FOTOGRAFÍA PUBLICITARIA"));
        repository.save(new Giro(749409, "SERVICIOS PERSONALES DE FOTOGRAFÍA"));
        repository.save(new Giro(749500, "SERVICIOS DE ENVASADO Y EMPAQUE"));
        repository.save(new Giro(749911, "SERVICIOS DE COBRANZA DE CUENTAS"));
        repository.save(new Giro(749912, "EVALUACIÓN Y CALIFICACIÓN DEL GRADO DE SOLVENCIA"));
        repository.save(new Giro(749913, "ASESORÍAS EN LA GESTIÓN DE LA COMPRA O VENTA DE PEQUENAS Y MEDIANAS EMPRESAS"));
        repository.save(new Giro(749921, "DISENADORES DE VESTUARIO"));
        repository.save(new Giro(749922, "DISENADORES DE INTERIORES"));
        repository.save(new Giro(749929, "OTROS DISENADORES N.C.P."));
        repository.save(new Giro(749931, "EMPRESAS DE TAQUIGRAFÍA"));
        repository.save(new Giro(749932, "SERVICIOS PERSONALES DE TRADUCCIÓN"));
        repository.save(new Giro(749933, "EMPRESAS DE TRADUCCIÓN E INTERPRETACIÓN"));
        repository.save(new Giro(749934, "SERVICIOS DE FOTOCOPIAS"));
        repository.save(new Giro(749940, "AGENCIAS DE CONTRATACIÓN DE ACTORES"));
        repository.save(new Giro(749950, "ACTIVIDADES DE SUBASTA (MARTILLEROS)"));
        repository.save(new Giro(749961, "GALERÍAS DE ARTE"));
        repository.save(new Giro(749962, "FERIAS DE EXPOSICIONES CON FINES EMPRESARIALES"));
        repository.save(new Giro(749970, "SERVICIOS DE CONTESTACIÓN DE LLAMADAS (CALL CENTER)"));
        repository.save(new Giro(749990, "OTRAS ACTIVIDADES EMPRESARIALES N.C.P."));
        repository.save(new Giro(751110, "GOBIERNO CENTRAL"));
        repository.save(new Giro(751120, "MUNICIPALIDADES"));
        repository.save(new Giro(751200, "ACTIVIDADES DEL PODER JUDICIAL"));
        repository.save(new Giro(751300, "ACTIVIDADES DEL PODER LEGISLATIVO"));
        repository.save(new Giro(752100, "RELACIONES EXTERIORES"));
        repository.save(new Giro(752200, "ACTIVIDADES DE DEFENSA"));
        repository.save(new Giro(752300, "ACTIVIDADES DE MANTENIMIENTO DEL ORDEN PÚBLICO Y DE SEGURIDAD"));
        repository.save(new Giro(753010, "ACTIVIDADES DE PLANES DE SEGURIDAD SOCIAL DE AFILIACIÓN OBLIGATORIA RELACIONADOS CON SALUD"));
        repository.save(new Giro(753020, "CAJAS DE COMPENSACIÓN"));
        repository.save(new Giro(753090, "OTRAS ACTIVIDADES DE PLANES DE SEGURIDAD SOCIAL DE AFILIACIÓN OBLIGATORIA"));
        repository.save(new Giro(801010, "ESTABLECIMIENTOS DE ENSEÑANZA PREESCOLAR"));
        repository.save(new Giro(801020, "ESTABLECIMIENTOS DE ENSEÑANZA PRIMARIA"));
        repository.save(new Giro(802100, "ESTABLECIMIENTOS DE ENSEÑANZA SECUNDARIA DE FORMACIÓN GENERAL"));
        repository.save(new Giro(802200, "ESTABLECIMIENTOS DE ENSEÑANZA SECUNDARIA DE FORMACIÓN TÉCNICA Y PROFESIONAL"));
        repository.save(new Giro(803010, "UNIVERSIDADES"));
        repository.save(new Giro(803020, "INSTITUTOS PROFESIONALES"));
        repository.save(new Giro(803030, "CENTROS DE FORMACIÓN TÉCNICA"));
        repository.save(new Giro(809010, "ESTABLECIMIENTOS DE ENSEÑANZA PRIMARIA Y SECUNDARIA PARA ADULTOS"));
        repository.save(new Giro(809020, "ESTABLECIMIENTOS DE ENSEÑANZA PREUNIVERSITARIA"));
        repository.save(new Giro(809030, "EDUCACIÓN EXTRAESCOLAR (ESCUELA DE CONDUCCIÓN"));
        repository.save(new Giro(809041, "EDUCACIÓN A DISTANCIA (INTERNET"));
        repository.save(new Giro(809049, "SERVICIOS PERSONALES DE EDUCACIÓN"));
        repository.save(new Giro(851110, "HOSPITALES Y CLÍNICAS"));
        repository.save(new Giro(851120, "CLÍNICAS PSIQUIATRICAS"));
        repository.save(new Giro(851211, "SERVICIOS DE MÉDICOS EN FORMA INDEPENDIENTE"));
        repository.save(new Giro(851212, "ESTABLECIMIENTOS MÉDICOS DE ATENCIÓN AMBULATORIA (CENTROS MÉDICOS)"));
        repository.save(new Giro(851221, "SERVICIOS DE ODONTÓLOGOS EN FORMA INDEPENDIENTE"));
        repository.save(new Giro(851222, "CENTROS DE ATENCIÓN ODONTOLÓGICA"));
        repository.save(new Giro(851910, "LABORATORIOS CLÍNICOS, INCLUYE BANCOS DE SANGRE"));
        repository.save(new Giro(851920, "OTROS PROFESIONALES DE LA SALUD"));
        repository.save(new Giro(851990, "OTRAS ACTIVIDADES EMPRESARIALES RELACIONADAS CON LA SALUD HUMANA"));
        repository.save(new Giro(852010, "ACTIVIDADES DE CLÍNICAS VETERINARIAS"));
        repository.save(new Giro(852021, "SERVICIOS DE MÉDICOS VETERINARIOS EN FORMA INDEPENDIENTE"));
        repository.save(new Giro(852029, "SERVICIOS DE OTROS PROFESIONALES INDEPENDIENTES EN EL ÁREA VETERINARIA"));
        repository.save(new Giro(853100, "SERVICIOS SOCIALES CON ALOJAMIENTO"));
        repository.save(new Giro(853200, "SERVICIOS SOCIALES SIN ALOJAMIENTO"));
        repository.save(new Giro(900010, "SERVICIOS DE VERTEDEROS"));
        repository.save(new Giro(900020, "BARRIDO DE EXTERIORES"));
        repository.save(new Giro(900030, "RECOGIDA Y ELIMINACIÓN DE DESECHOS"));
        repository.save(new Giro(900040, "SERVICIOS DE EVACUACIÓN DE RILES Y AGUAS SERVIDAS"));
        repository.save(new Giro(900050, "SERVICIOS DE TRATAMIENTO DE RILES Y AGUAS SERVIDAS"));
        repository.save(new Giro(900090, "OTRAS ACTIVIDADES DE MANEJO DE DESPERDICIOS"));
        repository.save(new Giro(911100, "ACTIVIDADES DE ORGANIZACIONES EMPRESARIALES Y DE EMPLEADORES"));
        repository.save(new Giro(911210, "COLEGIOS PROFESIONALES"));
        repository.save(new Giro(911290, "ACTIVIDADES DE OTRAS ORGANIZACIONES PROFESIONALES"));
        repository.save(new Giro(912000, "ACTIVIDADES DE SINDICATOS"));
        repository.save(new Giro(919100, "ACTIVIDADES DE ORGANIZACIONES RELIGIOSAS"));
        repository.save(new Giro(919200, "ACTIVIDADES DE ORGANIZACIONES POLÍTICAS"));
        repository.save(new Giro(919910, "CENTROS DE MADRES Y UNIDADES VECINALES Y COMUNALES"));
        repository.save(new Giro(919920, "CLUBES SOCIALES"));
        repository.save(new Giro(919930, "SERVICIOS DE INSTITUTOS DE ESTUDIOS"));
        repository.save(new Giro(919990, "ACTIVIDADES DE OTRAS ASOCIACIONES N.C.P."));
        repository.save(new Giro(921110, "PRODUCCIÓN DE PELÍCULAS CINEMATOGRÁFICAS"));
        repository.save(new Giro(921120, "DISTRIBUIDORA CINEMATOGRÁFICAS"));
        repository.save(new Giro(921200, "EXHIBICIÓN DE FILMES Y VIDEOCINTAS"));
        repository.save(new Giro(921310, "ACTIVIDADES DE TELEVISIÓN"));
        repository.save(new Giro(921320, "ACTIVIDADES DE RADIO"));
        repository.save(new Giro(921411, "SERVICIOS DE PRODUCCIÓN DE RECITALES Y OTROS EVENTOS MUSICALES MASIVOS"));
        repository.save(new Giro(921419, "SERVICIOS DE PRODUCCIÓN TEATRAL Y OTROS N.C.P."));
        repository.save(new Giro(921420, "ACTIVIDADES EMPRESARIALES DE ARTISTAS"));
        repository.save(new Giro(921430, "ACTIVIDADES ARTÍSTICAS, FUNCIONES DE ARTISTAS, ACTORES, MÚSICOS, CONFERENCISTAS, OTROS"));
        repository.save(new Giro(921490, "AGENCIAS DE VENTA DE BILLETES DE TEATRO"));
        repository.save(new Giro(921911, "INSTRUCTORES DE DANZA"));
        repository.save(new Giro(921912, "ACTIVIDADES DE DISCOTECAS"));
        repository.save(new Giro(921920, "ACTIVIDADES DE PARQUES DE ATRACCIONES Y CENTROS SIMILARES"));
        repository.save(new Giro(921930, "ESPECTÁCULOS CIRCENSES"));
        repository.save(new Giro(921990, "OTRAS ACTIVIDADES DE ENTRETENIMIENTO N.C.P."));
        repository.save(new Giro(922001, "AGENCIAS DE NOTICIAS"));
        repository.save(new Giro(922002, "SERVICIOS PERIODÍSTICOS PRESTADO POR PROFESIONALES"));
        repository.save(new Giro(923100, "ACTIVIDADES DE BIBLIOTECAS Y ARCHIVOS"));
        repository.save(new Giro(923200, "ACTIVIDADES DE MUSEOS Y PRESERVACIÓN DE LUGARES Y EDIFICIOS HISTÓRICOS"));
        repository.save(new Giro(923300, "ACTIVIDADES DE JARDINES BOTÁNICOS Y ZOOLÓGICOS Y DE PARQUES NACIONALES"));
        repository.save(new Giro(924110, "EXPLOTACIÓN DE INSTALACIONES ESPECIALIZADAS PARA LAS PRACTICAS DEPORTIVAS"));
        repository.save(new Giro(924120, "ACTIVIDADES DE CLUBES DE DEPORTES Y ESTADIOS"));
        repository.save(new Giro(924131, "FUTBOL PROFESIONAL"));
        repository.save(new Giro(924132, "FUTBOL AMATEUR"));
        repository.save(new Giro(924140, "HIPÓDROMOS"));
        repository.save(new Giro(924150, "PROMOCIÓN Y ORGANIZACIÓN DE ESPECTÁCULOS DEPORTIVOS"));
        repository.save(new Giro(924160, "ESCUELAS PARA DEPORTES"));
        repository.save(new Giro(924190, "OTRAS ACTIVIDADES RELACIONADAS AL DEPORTE N.C.P."));
        repository.save(new Giro(924910, "SISTEMAS DE JUEGOS DE AZAR MASIVOS."));
        repository.save(new Giro(924920, "ACTIVIDADES DE CASINO DE JUEGOS"));
        repository.save(new Giro(924930, "SALAS DE BILLAR"));
        repository.save(new Giro(924940, "CONTRATACIÓN DE ACTORES PARA CINE"));
        repository.save(new Giro(924990, "OTROS SERVICIOS DE DIVERSIÓN Y ESPARCIMIENTOS N.C.P."));
        repository.save(new Giro(930100, "LAVADO Y LIMPIEZA DE PRENDAS DE TELA Y DE PIEL"));
        repository.save(new Giro(930200, "PELUQUERÍAS Y SALONES DE BELLEZA"));
        repository.save(new Giro(930310, "SERVICIOS FUNERARIOS"));
        repository.save(new Giro(930320, "SERVICIOS EN CEMENTERIOS"));
        repository.save(new Giro(930330, "SERVICIOS DE CARROZAS FÚNEBRES (TRANSPORTE DE CADÁVERES)"));
        repository.save(new Giro(930390, "OTRAS ACTIVIDADES DE SERVICIOS FUNERARIOS Y OTRAS ACTIVIDADES CONEXAS"));
        repository.save(new Giro(930910, "ACTIVIDADES DE MANTENIMIENTO FÍSICO CORPORAL (BAÑOS"));
        repository.save(new Giro(930990, "OTRAS ACTIVIDADES DE SERVICIOS PERSONALES N.C.P."));
        repository.save(new Giro(950001, "HOGARES PRIVADOS INDIVIDUALES CON SERVICIO DOMÉSTICO"));
        repository.save(new Giro(950002, "CONSEJO DE ADMINISTRACIÓN DE EDIFICIOS Y CONDOMINIOS"));
        repository.save(new Giro(990000, "ORGANIZACIONES Y ÓRGANOS EXTRATERRITORIALES"));
        }
    }

    // Petición GET (Mostrar Todos)  
    @CrossOrigin
    @RequestMapping(value = "/bodega/giro/", method = GET)
    public Collection<Giro> getGiros() {
        return repository.listaTodo();
    }

    //Buscar a un Giro
    @CrossOrigin
    @RequestMapping(value = "/bodega/giro/{id}", method = GET)
    public Optional<Giro> getGiro(@PathVariable long id) {
        return repository.findById(id);
    }

    // Petición POST(Agregar)
    @CrossOrigin
    @RequestMapping(value = "/bodega/giro/", method = POST)
    @ResponseStatus(HttpStatus.CREATED)
    public Giro nuevoGiro(@Valid @RequestBody Giro giro) {
        repository.save(giro);

        return giro;
    }

    // Petición PUT (Editar)
    @CrossOrigin
    @RequestMapping(value = "/bodega/giro/{id}", method = PUT)
    public ResponseEntity<Optional<Giro>> actualizarGiro(@Valid @PathVariable long id, @RequestBody Giro actualizarGiro) {
        Optional<Giro> giro = repository.findById(id);
        if (giro != null) {

            actualizarGiro.setId(id);
            repository.save(actualizarGiro);
            return new ResponseEntity<>(giro, HttpStatus.OK);
        } else {
            return new ResponseEntity<>(HttpStatus.NOT_FOUND);
        }
    }

    // Petición DELETE(Eliminar)
    @CrossOrigin
    @RequestMapping(value = "/bodega/giro/{id}", method = DELETE)
    public ResponseEntity<Optional<Giro>> eliminarGiro(@PathVariable long id) {
        Optional<Giro> giro = repository.findById(id);
        repository.deleteById(id);
        if (giro != null) {
            return new ResponseEntity<>(giro, HttpStatus.OK);
        } else {
            return new ResponseEntity<>(HttpStatus.NOT_FOUND);
        }
    }
}
